POST http://localhost:8085/add
Content-Type: application/json

{
  "data": "Content 3"
}

###
GET http://localhost:8085/blockchain
Content-Type: application/json

###
GET http://localhost:8085/pool
Content-Type: application/json

###


###
POST http://localhost:8081/peer/add
Content-Type: application/json

{
  "host": "http://localhost:8080"
}
###
