POST http://localhost:8080/add
Content-Type: application/json

{
  "data": "Content"
}

###
GET http://localhost:8080/blockchain
Content-Type: application/json

###
GET http://localhost:8080/pool
Content-Type: application/json

###
